In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dates = pd.date_range('20130101', periods=8)
print(dates)
s1 = pd.Series([1,2,3,4,5,6,7,8], index=pd.date_range('20130102', periods=8))

df = pd.DataFrame(np.random.randn(8,4), index=dates, columns=list('ABCD'))

#add s1 a df
df['F'] = s1
#asigno a a en 0  valor 0
df.at[dates[0],'A']=0
print('[--]')
print(df)
#al i[0]j[1]le asigno 0 
df.iat[0,1]=0
print('[-------]')
print(df)
#a la columna d le asigno 5 a toda la profundidad del df en la columna D
df.loc[:,'D']=np.array([5]*len(df))
print('[-------]')
print(df)
# POner a negativo todo lo que sea mayor que 0
df2=df.copy()
df2[df2>0]=-df2

print('[-------]')
print(df2)
# asigno un new data frama con los 4 primeros elementos de la columna
# dates de 0a 4 y adiciono una columna E vacia
df1=df.reindex(index=dates[0:4],columns=list(df.columns)+['E'])
print('[-------]')
print(df1)
# 
print(df1.columns)
#asigno los valores de 1 a las 2 primeras
# filas donde las fechas sean 
# iguales  a las de 0 a 1 de dates
df1.loc[dates[0]:dates[1],'E']=1

print('[-------]')
print(df1)

#eleminar  todas las filas que tengas valor nan
df1.dropna()
print('[-------filas que tengas valor nan]')
print(df1)
#rellenar los elementos que no tengan valor 
df1.fillna(4)
print('[-------]')
print(df1)

# muestra una matriz de boolean donde sean nan o no
df1.isna()
print('[-------]')
print(df1)
#promedio de la matriz total ordenada por columnas
print('[-------mean]')
print(df1.mean())

#promedio por filas 
print('[-------mean 1]')
print(df1.mean(1))

s = pd.Series([1,3,5,np.nan,6,8,12,12], index=dates).shift(2)
print('[-------new s]')
print (s)

#uniando doa matrices
print('[-------new s un]')
print(df.sub(s,axis='index'))

#aplicando funciones a los datos
print('[------- np.cumsum eje x]')
print(df.cumsum(axis=1))

print('[------- np.cumsum eje y]')
print(df.cumsum(axis=0))

#

print('[------- aply lamdas maximo menos minimo de cada columna')
df.apply(lambda x: x.max() - x.min())

#histogramas 
#creando matriz con ramdom

s= pd.Series(np.random.randint(0,7,size=10))
print(s)

#contar los valores de una matriz
s.value_counts()

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')
[--]
                   A         B         C         D    F
2013-01-01  0.000000 -3.371195  0.078617 -0.364417  NaN
2013-01-02 -0.269670 -1.143940  0.421482  1.405696  1.0
2013-01-03 -0.149746 -1.026716 -1.167214 -0.275767  2.0
2013-01-04  0.801990  0.685072  2.147950  0.826373  3.0
2013-01-05 -0.326059  0.743033 -0.863893 -0.273924  4.0
2013-01-06  0.076547  0.821545 -0.905181  0.073160  5.0
2013-01-07  0.109706 -1.514161  1.399900 -0.133411  6.0
2013-01-08  0.528634  0.424525 -2.544529  0.775911  7.0
[-------]
                   A         B         C         D    F
2013-01-01  0.000000  0.000000  0.078617 -0.364417  NaN
2013-01-02 -0.269670 -1.143940  0.421482  1.405696  1.0
2013-01-03 -0.149746 -1.026716 -1.167214 -0.275767  2.0
2013-01-04  0.801990  0.685072  2.147950  0.826373  3.0
2013-01-05 -0.326059  0.743033 -0.863893 -0.273924  4.0
2013-01-06  0.076547  0.821545 -0.905181  0.073160  5.0
2013-01-07  0.109706 -1.514161  1.399900 -0.133411  6.0
2013-01-08  0.528634  0.424525 -2.544529  0.775911  7.0
[-------]
                   A         B         C  D    F
2013-01-01  0.000000  0.000000  0.078617  5  NaN
2013-01-02 -0.269670 -1.143940  0.421482  5  1.0
2013-01-03 -0.149746 -1.026716 -1.167214  5  2.0
2013-01-04  0.801990  0.685072  2.147950  5  3.0
2013-01-05 -0.326059  0.743033 -0.863893  5  4.0
2013-01-06  0.076547  0.821545 -0.905181  5  5.0
2013-01-07  0.109706 -1.514161  1.399900  5  6.0
2013-01-08  0.528634  0.424525 -2.544529  5  7.0
[-------]
                   A         B         C  D    F
2013-01-01  0.000000  0.000000 -0.078617 -5  NaN
2013-01-02 -0.269670 -1.143940 -0.421482 -5 -1.0
2013-01-03 -0.149746 -1.026716 -1.167214 -5 -2.0
2013-01-04 -0.801990 -0.685072 -2.147950 -5 -3.0
2013-01-05 -0.326059 -0.743033 -0.863893 -5 -4.0
2013-01-06 -0.076547 -0.821545 -0.905181 -5 -5.0
2013-01-07 -0.109706 -1.514161 -1.399900 -5 -6.0
2013-01-08 -0.528634 -0.424525 -2.544529 -5 -7.0
[-------]
                   A         B         C  D    F   E
2013-01-01  0.000000  0.000000  0.078617  5  NaN NaN
2013-01-02 -0.269670 -1.143940  0.421482  5  1.0 NaN
2013-01-03 -0.149746 -1.026716 -1.167214  5  2.0 NaN
2013-01-04  0.801990  0.685072  2.147950  5  3.0 NaN
Index(['A', 'B', 'C', 'D', 'F', 'E'], dtype='object')
[-------]
                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.078617  5  NaN  1.0
2013-01-02 -0.269670 -1.143940  0.421482  5  1.0  1.0
2013-01-03 -0.149746 -1.026716 -1.167214  5  2.0  NaN
2013-01-04  0.801990  0.685072  2.147950  5  3.0  NaN
[-------filas que tengas valor nan]
                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.078617  5  NaN  1.0
2013-01-02 -0.269670 -1.143940  0.421482  5  1.0  1.0
2013-01-03 -0.149746 -1.026716 -1.167214  5  2.0  NaN
2013-01-04  0.801990  0.685072  2.147950  5  3.0  NaN
[-------]
                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.078617  5  NaN  1.0
2013-01-02 -0.269670 -1.143940  0.421482  5  1.0  1.0
2013-01-03 -0.149746 -1.026716 -1.167214  5  2.0  NaN
2013-01-04  0.801990  0.685072  2.147950  5  3.0  NaN
[-------]
                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.078617  5  NaN  1.0
2013-01-02 -0.269670 -1.143940  0.421482  5  1.0  1.0
2013-01-03 -0.149746 -1.026716 -1.167214  5  2.0  NaN
2013-01-04  0.801990  0.685072  2.147950  5  3.0  NaN
[-------mean]
A    0.095643
B   -0.371396
C    0.370209
D    5.000000
F    2.000000
E    1.000000
dtype: float64
[-------mean 1]
2013-01-01    1.215723
2013-01-02    1.001312
2013-01-03    0.931265
2013-01-04    2.327002
Freq: D, dtype: float64
[-------new s]
2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
2013-01-07    6.0
2013-01-08    8.0
Freq: D, dtype: float64
[-------new s un]
                   A         B          C    D    F
2013-01-01       NaN       NaN        NaN  NaN  NaN
2013-01-02       NaN       NaN        NaN  NaN  NaN
2013-01-03 -1.149746 -2.026716  -2.167214  4.0  1.0
2013-01-04 -2.198010 -2.314928  -0.852050  2.0  0.0
2013-01-05 -5.326059 -4.256967  -5.863893  0.0 -1.0
2013-01-06       NaN       NaN        NaN  NaN  NaN
2013-01-07 -5.890294 -7.514161  -4.600100 -1.0  0.0
2013-01-08 -7.471366 -7.575475 -10.544529 -3.0 -1.0
[------- np.cumsum eje x]
                   A         B         C         D          F
2013-01-01  0.000000  0.000000  0.078617  5.078617        NaN
2013-01-02 -0.269670 -1.413610 -0.992128  4.007872   5.007872
2013-01-03 -0.149746 -1.176462 -2.343676  2.656324   4.656324
2013-01-04  0.801990  1.487062  3.635012  8.635012  11.635012
2013-01-05 -0.326059  0.416973 -0.446919  4.553081   8.553081
2013-01-06  0.076547  0.898092 -0.007089  4.992911   9.992911
2013-01-07  0.109706 -1.404456 -0.004556  4.995444  10.995444
2013-01-08  0.528634  0.953159 -1.591370  3.408630  10.408630
[------- np.cumsum eje y]
                   A         B         C     D     F
2013-01-01  0.000000  0.000000  0.078617   5.0   NaN
2013-01-02 -0.269670 -1.143940  0.500099  10.0   1.0
2013-01-03 -0.419417 -2.170656 -0.667115  15.0   3.0
2013-01-04  0.382574 -1.485584  1.480835  20.0   6.0
2013-01-05  0.056515 -0.742552  0.616943  25.0  10.0
2013-01-06  0.133061  0.078993 -0.288238  30.0  15.0
2013-01-07  0.242767 -1.435168  1.111662  35.0  21.0
2013-01-08  0.771401 -1.010643 -1.432866  40.0  28.0
[------- aply lamdas maximo menos minimo de cada columna
0    1
1    3
2    5
3    5
4    5
5    3
6    4
7    3
8    1
9    3
dtype: int32